import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Wix_Madefor_Text } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import {  SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'

const wix = Wix_Madefor_Text({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${wix.className} h-screen bg-[#f8f8f8]`}>
        <header className="h-[5vh]">
            <SignedOut>
              <SignInButton />
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
          </header>
          {children}
          <Toaster richColors expand closeButton />
          </body>
      </html>
    </ClerkProvider>
  );
}
